import { test, expect } from '@playwright/test'
import { createHmac } from 'node:crypto'
import path from 'node:path'

function otp(secret: string) {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
  const bits = [...secret].map((c) => alphabet.indexOf(c).toString(2).padStart(5, '0')).join('')
  const key = Buffer.from((bits.match(/.{8}/g) || []).map((b) => parseInt(b, 2)))
  const counter = Buffer.alloc(8)
  counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)))
  const hash = createHmac('sha1', key).update(counter).digest()
  const offset = hash[19] & 15
  return ((hash.readUInt32BE(offset) & 0x7fffffff) % 1000000).toString().padStart(6, '0')
}

test('account security, backup, 2FA and deletion', async ({ page }, testInfo) => {
  const email = `security-${Date.now()}-${testInfo.project.name}@example.com`
  let password = 'test-security-password-42'
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Create an account', exact: true }).click()
  await page.getByLabel('Your name').fill('Security Test')
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account', exact: true }).click()
  const navigate = async (name: string) => {
    if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: 'Open navigation' }).click()
    await page.getByRole('navigation').getByRole('button', { name, exact: true }).click()
  }
  await navigate('Settings')
  await expect(page.getByRole('heading', { name: 'Your account, under your control.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send verification link' })).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.screenshot({ path: `test-results/${testInfo.project.name}-security.png`, fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Change password', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Current password').fill(password)
  await dialog.getByLabel('New password', { exact: true }).fill('new-security-password-42')
  await dialog.getByLabel('Repeat new password').fill('new-security-password-42')
  await dialog.getByRole('button', { name: 'Change password', exact: true }).click()
  password = 'new-security-password-42'
  await expect(dialog).toBeHidden()
  await expect(page.getByText('Password changed. Other sessions have been signed out.')).toBeVisible()
  await page.getByRole('button', { name: 'Download all data', exact: true }).click()
  await dialog.getByLabel('Current password').fill(password)
  const pendingDownload = page.waitForEvent('download')
  await dialog.getByRole('button', { name: 'Download all data', exact: true }).click()
  const file = await pendingDownload
  const backupPath = testInfo.outputPath('backup.zip')
  await file.saveAs(backupPath)
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Restore backup', exact: true }).click()
  await dialog.getByLabel('SlipSnap backup ZIP').setInputFiles(backupPath)
  await dialog.getByLabel('Current password').fill(password)
  await dialog.getByLabel('Type RESTORE to confirm').fill('RESTORE')
  await dialog.getByRole('button', { name: 'Restore a backup', exact: true }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Set up 2FA', exact: true }).click()
  await dialog.getByLabel('Current password').fill(password)
  await dialog.getByRole('button', { name: 'Set up 2FA', exact: true }).click()
  const secret = await dialog.locator('.setup-key').textContent()
  await dialog.getByLabel('Current password').fill(password)
  await dialog.getByLabel('Authenticator or recovery code').fill(otp(secret!))
  await dialog.getByRole('button', { name: 'Confirm authenticator', exact: true }).click()
  await expect(dialog).toBeHidden()
  const codes = (await page.locator('.recovery-card pre').textContent())!.split('\n')
  expect(codes).toHaveLength(10)
  await page.getByRole('button', { name: 'I have saved my codes' }).click()
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByLabel('Email address').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByLabel('Authenticator / recovery code (if enabled)').fill(codes[0])
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await navigate('Settings')
  await expect(page.getByText('Enabled · 9 recovery codes left')).toBeVisible()
  await page.getByRole('button', { name: 'Turn off 2FA', exact: true }).click()
  await dialog.getByLabel('Current password').fill(password)
  await dialog.getByLabel('Authenticator or recovery code').fill(codes[1])
  await dialog.getByRole('button', { name: 'Turn off 2FA', exact: true }).click()
  await expect(dialog).toBeHidden()
  await navigate('Scan receipt')
  // Preview privacy test does not depend on the OCR engine.
  await page.route('**/api/receipts/upload', (route) => route.fulfill({ status: 503, json: { detail: 'Preview test' } }))
  await page.getByLabel('Upload bank slip file').setInputFiles(path.resolve('tests/fixtures/receipt.png'))
  await expect(page.getByText('Slip preview hidden', { exact: true })).toBeVisible()
  await expect(page.locator('.receipt-preview img')).toHaveCount(0)
  await page.getByRole('button', { name: 'Show original preview' }).click()
  await expect(page.locator('.receipt-preview img')).toBeVisible()
  await page.getByRole('button', { name: 'Hide preview', exact: true }).click()
  await expect(page.locator('.receipt-preview img')).toHaveCount(0)
  await navigate('Settings')
  await page.getByRole('button', { name: 'Delete account', exact: true }).click()
  await dialog.getByLabel('Current password').fill(password)
  await dialog.getByLabel('Type DELETE to confirm').fill('DELETE')
  await dialog.getByRole('button', { name: 'Delete account permanently', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Good to see you.' })).toBeVisible()
  expect(errors).toEqual([])
})
